export {default as RegionFilter} from './RegionFilter.vue'
export {default as PriceFilter} from './PriceFilter.vue'
export {default as AreaFilter} from './AreaFilter.vue'
export {default as BedroomFilter} from './BedroomFilter.vue'
export {default as FilterTags} from  './FilterTags.vue'